language: cpp
sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake	
    packages:
    - cmake

os:
  - linux

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then chmod ugo+x ./scripts/travis_install_dependencies.sh; ./scripts/travis_install_dependencies.sh; fi

before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then chmod ugo+x ./scripts/travis_prepare_cmake.sh; ./scripts/travis_prepare_cmake.sh; fi
  
script: 
  - cd travis-build
  - make install
  - cd ../travis-install
  - ls
