language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then  chmod ugo+x ./scripts/travis_install_dependencies.sh; ./scripts/travis_install_dependencies.sh; fi

script: 
  - ls /tmp/*
