language: cpp

addons:
  apt:
    sources:
    - kalakris-cmake	
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libxxf86vm-dev
    - gcc-4.9
    - g++-4.9
	
os:
  - linux

compiler:
  - gcc

before_install:
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then chmod ugo+x ./scripts/travis_install_dependencies.sh; ./scripts/travis_install_dependencies.sh; fi

before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then chmod ugo+x ./scripts/travis_prepare_cmake.sh; ./scripts/travis_prepare_cmake.sh; fi
  
script: 
  - cd travis-build
  - make install
  - cd ../travis-install
  - ls
